// Downloads EasyList and its regional lists and writes lib/adlists.js: their network rules (no
// cosmetic rules), each list's name, version and languages. The ads Chrome's cut-down list misses are found
// with these. Run on each release: npm run adlists.
// EasyList is © The EasyList authors; the regional lists are by their own maintainers, each under its
// own licence. Each list's licence and attribution, from its own header, go to lib/adlists-LICENSE.txt.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { decides, parseRule } from '../lib/adlist.js';

const ABP = 'https://easylist-downloads.adblockplus.org/';
export const SOURCES = [
  ['EasyList', 'https://easylist.to/easylist/easylist.txt', ['*']],
  ['EasyList Spanish', `${ABP}easylistspanish.txt`, ['es', 'ca', 'gl', 'eu']],
  ['Liste FR', `${ABP}liste_fr.txt`, ['fr']],
  ['EasyList Germany', 'https://easylist.to/easylistgermany/easylistgermany.txt', ['de']],
  ['EasyList Italy', `${ABP}easylistitaly.txt`, ['it']],
  ['EasyList Portuguese', `${ABP}easylistportuguese.txt`, ['pt']],
  ['EasyList Dutch', `${ABP}easylistdutch.txt`, ['nl']],
  ['EasyList Polish', `${ABP}easylistpolish.txt`, ['pl']],
  ['EasyList Lithuania', `${ABP}easylistlithuania.txt`, ['lt']],
  ['EasyList Czech and Slovak', `${ABP}easylistczechslovak.txt`, ['cs', 'sk']],
  ['ROList', `${ABP}rolist.txt`, ['ro']],
  ['Bulgarian list', `${ABP}bulgarian_list.txt`, ['bg']],
  ['RU AdList', `${ABP}ruadlist.txt`, ['ru', 'uk', 'be', 'kk', 'uz']],
  ['EasyList China', `${ABP}easylistchina.txt`, ['zh']],
  ['KoreanList', `${ABP}koreanlist.txt`, ['ko']],
  ['IndianList', `${ABP}indianlist.txt`, ['hi', 'bn', 'ta', 'te', 'mr', 'gu', 'kn', 'ml', 'pa']],
  ['ABPVN List', `${ABP}abpvn.txt`, ['vi']],
  ['ABPindo', `${ABP}abpindo.txt`, ['id', 'ms']],
  ['Liste AR', `${ABP}liste_ar.txt`, ['ar']],
];

// The lines of a list's header that say what it is, who makes it and under what terms, verbatim: its
// comments before the first rule or section, without the update bookkeeping. Copied whole, as the
// lists word these in their own languages (RU AdList: "Лицензия CC-BY", its authors in prose).
const BOOKKEEPING = /^(checksum|version|last modified|last change|expires|commit|diff-path|diff-expires|id)\s*:/i;
function headerLines(text) {
  const lines = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('[')) continue; // [Adblock Plus 2.0]
    if (!line.startsWith('!') || /[-=]{5}/.test(line)) break; // the first rule, or the first section
    if (!/^!(\s|$)/.test(line)) continue; // a rule commented out
    const body = line.slice(1).trim();
    if (body && !BOOKKEEPING.test(body) && !/^\*\*\*.*\*\*\*$/.test(body)) lines.push(line);
  }
  return lines;
}

const root = fileURLToPath(new URL('../', import.meta.url));
const lists = [];
const rules = {}; // list name → rules (a rule in two lists is in both)
const headers = {}; // list name → its header lines (lib/adlists-LICENSE.txt)
let total = 0;
for (const [name, url, langs] of SOURCES) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${name}: HTTP ${response.status}`);
  const text = await response.text();
  const version = text.match(/^! Version: (\S+)/m)?.[1] ?? 'unknown';
  const kept = new Set();
  for (const line of text.split(/\r?\n/)) {
    // Only rules that decide (lib/adlist.js): the rest would never be used.
    const rule = parseRule(line);
    if (rule && decides(rule)) kept.add(line.trim());
  }
  rules[name] = [...kept];
  total += kept.size;
  lists.push({ name, version, langs });
  headers[name] = headerLines(text);
  console.log(`${name} ${version}: ${kept.size} rules`);
}
const source = `// Generated by scripts/build-adlists.mjs — do not edit. The rules that decide (exceptions and
// host-anchored blocking rules) of EasyList and its regional lists, per list, with each list's page
// languages. EasyList © The EasyList authors; regional lists by their maintainers — each list's
// licence and attribution in lib/adlists-LICENSE.txt.
export const LISTS = ${JSON.stringify(lists)};
export const RULES = ${JSON.stringify(rules)};
`;
writeFileSync(`${root}lib/adlists.js`, source);
const block = (l) => [
  `${l.name} (version ${l.version})`,
  ...headers[l.name],
  ...(headers[l.name].some((line) => /licen[csz]|лиценз/i.test(line)) ? [] : ['(Its header states no licence.)']),
].join('\n');
writeFileSync(`${root}lib/adlists-LICENSE.txt`, `The network rules in lib/adlists.js come from the lists below: EasyList, and the regional lists, each used on pages in its languages. Only their network rules that name a host, and their exception rules (those whose options the extension reads), are used, unmodified.

Each list is the work of its own authors and is used under its own licence. EasyList is © The EasyList authors (https://easylist.to/); the regional lists are by their maintainers. For each list, its version and the lines of its header that say what it is, who makes it and under what terms, copied verbatim (without the update bookkeeping).

${lists.map(block).join('\n\n')}
`);
const mb = Buffer.byteLength(source) / 1e6;
console.log(`lib/adlists.js: ${total} rules, ${mb.toFixed(2)} MB`);
if (mb > 5) console.warn('Over 5 MB: revisit which lists are bundled (spec decision 3).');
